inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-github:
    - config/default_edge.yml
    - config/rails_edge.yml

AsciiComments:
  Enabled: false

Style/TrailingWhitespace:
  Enabled: true

ClassAndModuleChildren:
  Enabled: false
