version: '3'
services:
  db:
    container_name: "mysql"
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'

  app:
    container_name: "rails"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
      DB_HOST: db
    command: bash ./docker.sh
    ports:
      - '8888:8888'
    volumes:
      - .:/app_root
    depends_on:
      - db
