version: '3.7'
services:
  db:
    container_name: 'mysql'
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'

  app:
    container_name: 'rails'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
      DB_HOST: db
    command: /bin/sh -c 'rm -rf tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0'
    ports:
      - '3000:3000'
    volumes:
      - .:/app_root
    depends_on:
      - db
    tty: true
    stdin_open: true
